/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class planner_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[3]
     */
    public float p_des[];

    /**
     * LCM Type: float[4][3]
     */
    public float foot_pDes[][];

    /**
     * LCM Type: float[3]
     */
    public float pw_[];

    /**
     * LCM Type: float[4][3]
     */
    public float foot_pw_[][];

    /**
     * LCM Type: float[4][3]
     */
    public float pf_init_[][];

    /**
     * LCM Type: float[4][3]
     */
    public float foot_vdes[][];

    /**
     * LCM Type: float[3]
     */
    public float rpy_des_[];

    /**
     * LCM Type: float[4][2]
     */
    public float pf_rel[][];

    /**
     * LCM Type: float[3]
     */
    public float parse_data[];

 
    public planner_lcmt()
    {
        p_des = new float[3];
        foot_pDes = new float[4][3];
        pw_ = new float[3];
        foot_pw_ = new float[4][3];
        pf_init_ = new float[4][3];
        foot_vdes = new float[4][3];
        rpy_des_ = new float[3];
        pf_rel = new float[4][2];
        parse_data = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb8e474d594826486L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.planner_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.planner_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_des[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.foot_pDes[a][b]); 
            }
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.pw_[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.foot_pw_[a][b]); 
            }
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.pf_init_[a][b]); 
            }
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.foot_vdes[a][b]); 
            }
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_des_[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 2; b++) {
                outs.writeFloat(this.pf_rel[a][b]); 
            }
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.parse_data[a]); 
        }
 
    }
 
    public planner_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public planner_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.planner_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.planner_lcmt o = new lcmtypes.planner_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.p_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_des[a] = ins.readFloat();
        }
 
        this.foot_pDes = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.foot_pDes[a][b] = ins.readFloat();
            }
        }
 
        this.pw_ = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.pw_[a] = ins.readFloat();
        }
 
        this.foot_pw_ = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.foot_pw_[a][b] = ins.readFloat();
            }
        }
 
        this.pf_init_ = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.pf_init_[a][b] = ins.readFloat();
            }
        }
 
        this.foot_vdes = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.foot_vdes[a][b] = ins.readFloat();
            }
        }
 
        this.rpy_des_ = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_des_[a] = ins.readFloat();
        }
 
        this.pf_rel = new float[(int) 4][(int) 2];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 2; b++) {
                this.pf_rel[a][b] = ins.readFloat();
            }
        }
 
        this.parse_data = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.parse_data[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.planner_lcmt copy()
    {
        lcmtypes.planner_lcmt outobj = new lcmtypes.planner_lcmt();
        outobj.p_des = new float[(int) 3];
        System.arraycopy(this.p_des, 0, outobj.p_des, 0, 3); 
        outobj.foot_pDes = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.foot_pDes[a], 0, outobj.foot_pDes[a], 0, 3);        }
 
        outobj.pw_ = new float[(int) 3];
        System.arraycopy(this.pw_, 0, outobj.pw_, 0, 3); 
        outobj.foot_pw_ = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.foot_pw_[a], 0, outobj.foot_pw_[a], 0, 3);        }
 
        outobj.pf_init_ = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.pf_init_[a], 0, outobj.pf_init_[a], 0, 3);        }
 
        outobj.foot_vdes = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.foot_vdes[a], 0, outobj.foot_vdes[a], 0, 3);        }
 
        outobj.rpy_des_ = new float[(int) 3];
        System.arraycopy(this.rpy_des_, 0, outobj.rpy_des_, 0, 3); 
        outobj.pf_rel = new float[(int) 4][(int) 2];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.pf_rel[a], 0, outobj.pf_rel[a], 0, 2);        }
 
        outobj.parse_data = new float[(int) 3];
        System.arraycopy(this.parse_data, 0, outobj.parse_data, 0, 3); 
        return outobj;
    }
 
}

