/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class quadruped_model_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[4][3]
     */
    public float pGC[][];

    /**
     * LCM Type: float[4][3]
     */
    public float vGC[][];

    /**
     * LCM Type: float[3]
     */
    public float base_omega[];

    /**
     * LCM Type: float[3]
     */
    public float base_vel[];

    /**
     * LCM Type: float[3]
     */
    public float base_pos[];

    /**
     * LCM Type: float[3]
     */
    public float base_rpy[];

 
    public quadruped_model_lcmt()
    {
        pGC = new float[4][3];
        vGC = new float[4][3];
        base_omega = new float[3];
        base_vel = new float[3];
        base_pos = new float[3];
        base_rpy = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x95d1ba66b15a5764L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.quadruped_model_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.quadruped_model_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.pGC[a][b]); 
            }
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.vGC[a][b]); 
            }
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.base_omega[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.base_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.base_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.base_rpy[a]); 
        }
 
    }
 
    public quadruped_model_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public quadruped_model_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.quadruped_model_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.quadruped_model_lcmt o = new lcmtypes.quadruped_model_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.pGC = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.pGC[a][b] = ins.readFloat();
            }
        }
 
        this.vGC = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.vGC[a][b] = ins.readFloat();
            }
        }
 
        this.base_omega = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.base_omega[a] = ins.readFloat();
        }
 
        this.base_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.base_vel[a] = ins.readFloat();
        }
 
        this.base_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.base_pos[a] = ins.readFloat();
        }
 
        this.base_rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.base_rpy[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.quadruped_model_lcmt copy()
    {
        lcmtypes.quadruped_model_lcmt outobj = new lcmtypes.quadruped_model_lcmt();
        outobj.pGC = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.pGC[a], 0, outobj.pGC[a], 0, 3);        }
 
        outobj.vGC = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.vGC[a], 0, outobj.vGC[a], 0, 3);        }
 
        outobj.base_omega = new float[(int) 3];
        System.arraycopy(this.base_omega, 0, outobj.base_omega, 0, 3); 
        outobj.base_vel = new float[(int) 3];
        System.arraycopy(this.base_vel, 0, outobj.base_vel, 0, 3); 
        outobj.base_pos = new float[(int) 3];
        System.arraycopy(this.base_pos, 0, outobj.base_pos, 0, 3); 
        outobj.base_rpy = new float[(int) 3];
        System.arraycopy(this.base_rpy, 0, outobj.base_rpy, 0, 3); 
        return outobj;
    }
 
}

