/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class rc_lcmt implements lcm.lcm.LCMEncodable
{
    public int mode;

    /**
     * LCM Type: float[2]
     */
    public float p_des[];

    public float height_variation;

    /**
     * LCM Type: float[3]
     */
    public float v_des[];

    /**
     * LCM Type: float[3]
     */
    public float rpy_des[];

    /**
     * LCM Type: float[3]
     */
    public float omega_des[];

    /**
     * LCM Type: float[3]
     */
    public float variables[];

    public float step_height;

 
    public rc_lcmt()
    {
        p_des = new float[2];
        v_des = new float[3];
        rpy_des = new float[3];
        omega_des = new float[3];
        variables = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3b0653e7596b6479L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.rc_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.rc_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.mode); 
 
        for (int a = 0; a < 2; a++) {
            outs.writeFloat(this.p_des[a]); 
        }
 
        outs.writeFloat(this.height_variation); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.omega_des[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.variables[a]); 
        }
 
        outs.writeFloat(this.step_height); 
 
    }
 
    public rc_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public rc_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.rc_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.rc_lcmt o = new lcmtypes.rc_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mode = ins.readInt();
 
        this.p_des = new float[(int) 2];
        for (int a = 0; a < 2; a++) {
            this.p_des[a] = ins.readFloat();
        }
 
        this.height_variation = ins.readFloat();
 
        this.v_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_des[a] = ins.readFloat();
        }
 
        this.rpy_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_des[a] = ins.readFloat();
        }
 
        this.omega_des = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.omega_des[a] = ins.readFloat();
        }
 
        this.variables = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.variables[a] = ins.readFloat();
        }
 
        this.step_height = ins.readFloat();
 
    }
 
    public lcmtypes.rc_lcmt copy()
    {
        lcmtypes.rc_lcmt outobj = new lcmtypes.rc_lcmt();
        outobj.mode = this.mode;
 
        outobj.p_des = new float[(int) 2];
        System.arraycopy(this.p_des, 0, outobj.p_des, 0, 2); 
        outobj.height_variation = this.height_variation;
 
        outobj.v_des = new float[(int) 3];
        System.arraycopy(this.v_des, 0, outobj.v_des, 0, 3); 
        outobj.rpy_des = new float[(int) 3];
        System.arraycopy(this.rpy_des, 0, outobj.rpy_des, 0, 3); 
        outobj.omega_des = new float[(int) 3];
        System.arraycopy(this.omega_des, 0, outobj.omega_des, 0, 3); 
        outobj.variables = new float[(int) 3];
        System.arraycopy(this.variables, 0, outobj.variables, 0, 3); 
        outobj.step_height = this.step_height;
 
        return outobj;
    }
 
}

