/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class sim_ground_truth_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[6]
     */
    public float p_w_[];

    /**
     * LCM Type: float[6]
     */
    public float v_w_[];

    /**
     * LCM Type: float[12]
     */
    public float q[];

    /**
     * LCM Type: float[12]
     */
    public float qd[];

 
    public sim_ground_truth_lcmt()
    {
        p_w_ = new float[6];
        v_w_ = new float[6];
        q = new float[12];
        qd = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9a053180cfb1f6fcL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.sim_ground_truth_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.sim_ground_truth_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 6; a++) {
            outs.writeFloat(this.p_w_[a]); 
        }
 
        for (int a = 0; a < 6; a++) {
            outs.writeFloat(this.v_w_[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.q[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.qd[a]); 
        }
 
    }
 
    public sim_ground_truth_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public sim_ground_truth_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.sim_ground_truth_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.sim_ground_truth_lcmt o = new lcmtypes.sim_ground_truth_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.p_w_ = new float[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.p_w_[a] = ins.readFloat();
        }
 
        this.v_w_ = new float[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.v_w_[a] = ins.readFloat();
        }
 
        this.q = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.q[a] = ins.readFloat();
        }
 
        this.qd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.qd[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.sim_ground_truth_lcmt copy()
    {
        lcmtypes.sim_ground_truth_lcmt outobj = new lcmtypes.sim_ground_truth_lcmt();
        outobj.p_w_ = new float[(int) 6];
        System.arraycopy(this.p_w_, 0, outobj.p_w_, 0, 6); 
        outobj.v_w_ = new float[(int) 6];
        System.arraycopy(this.v_w_, 0, outobj.v_w_, 0, 6); 
        outobj.q = new float[(int) 12];
        System.arraycopy(this.q, 0, outobj.q, 0, 12); 
        outobj.qd = new float[(int) 12];
        System.arraycopy(this.qd, 0, outobj.qd, 0, 12); 
        return outobj;
    }
 
}

