/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 * lcm-gen 1.5.1
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class wbc_test_data_lcmt implements lcm.lcm.LCMEncodable
{
    /**
     * LCM Type: float[12]
     */
    public float Fr_des[];

    /**
     * LCM Type: float[12]
     */
    public float Fr[];

    /**
     * LCM Type: float[4]
     */
    public float contact_esi[];

    /**
     * LCM Type: float[3]
     */
    public float ori_task_error[];

    /**
     * LCM Type: float[3]
     */
    public float pos_task_error[];

    /**
     * LCM Type: float[4][3]
     */
    public float link_pos_task_error[][];

    /**
     * LCM Type: float[4]
     */
    public float body_ori_cmd[];

    /**
     * LCM Type: float[3]
     */
    public float body_pos_cmd[];

    /**
     * LCM Type: float[3]
     */
    public float body_vel_cmd[];

    /**
     * LCM Type: float[3]
     */
    public float body_ang_vel_cmd[];

    /**
     * LCM Type: float[3]
     */
    public float body_rpy_cmd[];

    /**
     * LCM Type: float[3]
     */
    public float body_pos[];

    /**
     * LCM Type: float[3]
     */
    public float body_vel[];

    /**
     * LCM Type: float[4]
     */
    public float body_ori[];

    /**
     * LCM Type: float[3]
     */
    public float body_angl_vel[];

    /**
     * LCM Type: float[3]
     */
    public float body_rpy[];

    /**
     * LCM Type: float[12]
     */
    public float foot_pos_cmd[];

    /**
     * LCM Type: float[12]
     */
    public float foot_vel_cmd[];

    /**
     * LCM Type: float[12]
     */
    public float foot_acc_cmd[];

    /**
     * LCM Type: float[12]
     */
    public float foot_pos[];

    /**
     * LCM Type: float[12]
     */
    public float foot_vel[];

    /**
     * LCM Type: float[12]
     */
    public float jpos_cmd[];

    /**
     * LCM Type: float[12]
     */
    public float jvel_cmd[];

    /**
     * LCM Type: float[12]
     */
    public float jacc_cmd[];

    /**
     * LCM Type: float[12]
     */
    public float tau_ff[];

    /**
     * LCM Type: float[18]
     */
    public float opt_result[];

 
    public wbc_test_data_lcmt()
    {
        Fr_des = new float[12];
        Fr = new float[12];
        contact_esi = new float[4];
        ori_task_error = new float[3];
        pos_task_error = new float[3];
        link_pos_task_error = new float[4][3];
        body_ori_cmd = new float[4];
        body_pos_cmd = new float[3];
        body_vel_cmd = new float[3];
        body_ang_vel_cmd = new float[3];
        body_rpy_cmd = new float[3];
        body_pos = new float[3];
        body_vel = new float[3];
        body_ori = new float[4];
        body_angl_vel = new float[3];
        body_rpy = new float[3];
        foot_pos_cmd = new float[12];
        foot_vel_cmd = new float[12];
        foot_acc_cmd = new float[12];
        foot_pos = new float[12];
        foot_vel = new float[12];
        jpos_cmd = new float[12];
        jvel_cmd = new float[12];
        jacc_cmd = new float[12];
        tau_ff = new float[12];
        opt_result = new float[18];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x25c78209a6542039L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.wbc_test_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.wbc_test_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.Fr_des[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.Fr[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.contact_esi[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.ori_task_error[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.pos_task_error[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                outs.writeFloat(this.link_pos_task_error[a][b]); 
            }
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.body_ori_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_pos_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_ang_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_rpy_cmd[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_pos[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_vel[a]); 
        }
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.body_ori[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_angl_vel[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.body_rpy[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.foot_pos_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.foot_vel_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.foot_acc_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.foot_pos[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.foot_vel[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jpos_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jvel_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.jacc_cmd[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.tau_ff[a]); 
        }
 
        for (int a = 0; a < 18; a++) {
            outs.writeFloat(this.opt_result[a]); 
        }
 
    }
 
    public wbc_test_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public wbc_test_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.wbc_test_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.wbc_test_data_lcmt o = new lcmtypes.wbc_test_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.Fr_des = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.Fr_des[a] = ins.readFloat();
        }
 
        this.Fr = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.Fr[a] = ins.readFloat();
        }
 
        this.contact_esi = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.contact_esi[a] = ins.readFloat();
        }
 
        this.ori_task_error = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.ori_task_error[a] = ins.readFloat();
        }
 
        this.pos_task_error = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.pos_task_error[a] = ins.readFloat();
        }
 
        this.link_pos_task_error = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            for (int b = 0; b < 3; b++) {
                this.link_pos_task_error[a][b] = ins.readFloat();
            }
        }
 
        this.body_ori_cmd = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.body_ori_cmd[a] = ins.readFloat();
        }
 
        this.body_pos_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_pos_cmd[a] = ins.readFloat();
        }
 
        this.body_vel_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_vel_cmd[a] = ins.readFloat();
        }
 
        this.body_ang_vel_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_ang_vel_cmd[a] = ins.readFloat();
        }
 
        this.body_rpy_cmd = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_rpy_cmd[a] = ins.readFloat();
        }
 
        this.body_pos = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_pos[a] = ins.readFloat();
        }
 
        this.body_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_vel[a] = ins.readFloat();
        }
 
        this.body_ori = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.body_ori[a] = ins.readFloat();
        }
 
        this.body_angl_vel = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_angl_vel[a] = ins.readFloat();
        }
 
        this.body_rpy = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.body_rpy[a] = ins.readFloat();
        }
 
        this.foot_pos_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.foot_pos_cmd[a] = ins.readFloat();
        }
 
        this.foot_vel_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.foot_vel_cmd[a] = ins.readFloat();
        }
 
        this.foot_acc_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.foot_acc_cmd[a] = ins.readFloat();
        }
 
        this.foot_pos = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.foot_pos[a] = ins.readFloat();
        }
 
        this.foot_vel = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.foot_vel[a] = ins.readFloat();
        }
 
        this.jpos_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jpos_cmd[a] = ins.readFloat();
        }
 
        this.jvel_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jvel_cmd[a] = ins.readFloat();
        }
 
        this.jacc_cmd = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.jacc_cmd[a] = ins.readFloat();
        }
 
        this.tau_ff = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.tau_ff[a] = ins.readFloat();
        }
 
        this.opt_result = new float[(int) 18];
        for (int a = 0; a < 18; a++) {
            this.opt_result[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.wbc_test_data_lcmt copy()
    {
        lcmtypes.wbc_test_data_lcmt outobj = new lcmtypes.wbc_test_data_lcmt();
        outobj.Fr_des = new float[(int) 12];
        System.arraycopy(this.Fr_des, 0, outobj.Fr_des, 0, 12); 
        outobj.Fr = new float[(int) 12];
        System.arraycopy(this.Fr, 0, outobj.Fr, 0, 12); 
        outobj.contact_esi = new float[(int) 4];
        System.arraycopy(this.contact_esi, 0, outobj.contact_esi, 0, 4); 
        outobj.ori_task_error = new float[(int) 3];
        System.arraycopy(this.ori_task_error, 0, outobj.ori_task_error, 0, 3); 
        outobj.pos_task_error = new float[(int) 3];
        System.arraycopy(this.pos_task_error, 0, outobj.pos_task_error, 0, 3); 
        outobj.link_pos_task_error = new float[(int) 4][(int) 3];
        for (int a = 0; a < 4; a++) {
            System.arraycopy(this.link_pos_task_error[a], 0, outobj.link_pos_task_error[a], 0, 3);        }
 
        outobj.body_ori_cmd = new float[(int) 4];
        System.arraycopy(this.body_ori_cmd, 0, outobj.body_ori_cmd, 0, 4); 
        outobj.body_pos_cmd = new float[(int) 3];
        System.arraycopy(this.body_pos_cmd, 0, outobj.body_pos_cmd, 0, 3); 
        outobj.body_vel_cmd = new float[(int) 3];
        System.arraycopy(this.body_vel_cmd, 0, outobj.body_vel_cmd, 0, 3); 
        outobj.body_ang_vel_cmd = new float[(int) 3];
        System.arraycopy(this.body_ang_vel_cmd, 0, outobj.body_ang_vel_cmd, 0, 3); 
        outobj.body_rpy_cmd = new float[(int) 3];
        System.arraycopy(this.body_rpy_cmd, 0, outobj.body_rpy_cmd, 0, 3); 
        outobj.body_pos = new float[(int) 3];
        System.arraycopy(this.body_pos, 0, outobj.body_pos, 0, 3); 
        outobj.body_vel = new float[(int) 3];
        System.arraycopy(this.body_vel, 0, outobj.body_vel, 0, 3); 
        outobj.body_ori = new float[(int) 4];
        System.arraycopy(this.body_ori, 0, outobj.body_ori, 0, 4); 
        outobj.body_angl_vel = new float[(int) 3];
        System.arraycopy(this.body_angl_vel, 0, outobj.body_angl_vel, 0, 3); 
        outobj.body_rpy = new float[(int) 3];
        System.arraycopy(this.body_rpy, 0, outobj.body_rpy, 0, 3); 
        outobj.foot_pos_cmd = new float[(int) 12];
        System.arraycopy(this.foot_pos_cmd, 0, outobj.foot_pos_cmd, 0, 12); 
        outobj.foot_vel_cmd = new float[(int) 12];
        System.arraycopy(this.foot_vel_cmd, 0, outobj.foot_vel_cmd, 0, 12); 
        outobj.foot_acc_cmd = new float[(int) 12];
        System.arraycopy(this.foot_acc_cmd, 0, outobj.foot_acc_cmd, 0, 12); 
        outobj.foot_pos = new float[(int) 12];
        System.arraycopy(this.foot_pos, 0, outobj.foot_pos, 0, 12); 
        outobj.foot_vel = new float[(int) 12];
        System.arraycopy(this.foot_vel, 0, outobj.foot_vel, 0, 12); 
        outobj.jpos_cmd = new float[(int) 12];
        System.arraycopy(this.jpos_cmd, 0, outobj.jpos_cmd, 0, 12); 
        outobj.jvel_cmd = new float[(int) 12];
        System.arraycopy(this.jvel_cmd, 0, outobj.jvel_cmd, 0, 12); 
        outobj.jacc_cmd = new float[(int) 12];
        System.arraycopy(this.jacc_cmd, 0, outobj.jacc_cmd, 0, 12); 
        outobj.tau_ff = new float[(int) 12];
        System.arraycopy(this.tau_ff, 0, outobj.tau_ff, 0, 12); 
        outobj.opt_result = new float[(int) 18];
        System.arraycopy(this.opt_result, 0, outobj.opt_result, 0, 18); 
        return outobj;
    }
 
}

