"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class leg_control_data_lcmt(object):

    __slots__ = ["q", "qd", "p", "v", "tau_est", "tau_cmd"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[16], [16], [12], [12], [16], [16]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(16) ]
        """ LCM Type: float[16] """
        self.qd = [ 0.0 for dim0 in range(16) ]
        """ LCM Type: float[16] """
        self.p = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.v = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.tau_est = [ 0.0 for dim0 in range(16) ]
        """ LCM Type: float[16] """
        self.tau_cmd = [ 0.0 for dim0 in range(16) ]
        """ LCM Type: float[16] """

    def encode(self):
        buf = BytesIO()
        buf.write(leg_control_data_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>16f', *self.q[:16]))
        buf.write(struct.pack('>16f', *self.qd[:16]))
        buf.write(struct.pack('>12f', *self.p[:12]))
        buf.write(struct.pack('>12f', *self.v[:12]))
        buf.write(struct.pack('>16f', *self.tau_est[:16]))
        buf.write(struct.pack('>16f', *self.tau_cmd[:16]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != leg_control_data_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return leg_control_data_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = leg_control_data_lcmt()
        self.q = struct.unpack('>16f', buf.read(64))
        self.qd = struct.unpack('>16f', buf.read(64))
        self.p = struct.unpack('>12f', buf.read(48))
        self.v = struct.unpack('>12f', buf.read(48))
        self.tau_est = struct.unpack('>16f', buf.read(64))
        self.tau_cmd = struct.unpack('>16f', buf.read(64))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if leg_control_data_lcmt in parents: return 0
        tmphash = (0xbe0efb1889e314c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if leg_control_data_lcmt._packed_fingerprint is None:
            leg_control_data_lcmt._packed_fingerprint = struct.pack(">Q", leg_control_data_lcmt._get_hash_recursive([]))
        return leg_control_data_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", leg_control_data_lcmt._get_packed_fingerprint())[0]

