"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class planner_lcmt(object):

    __slots__ = ["p_des", "foot_pDes", "pw_", "foot_pw_", "pf_init_", "foot_vdes", "rpy_des_", "pf_rel", "parse_data"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[3], [4, 3], [3], [4, 3], [4, 3], [4, 3], [3], [4, 2], [3]]

    def __init__(self):
        self.p_des = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.foot_pDes = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]
        """ LCM Type: float[4][3] """
        self.pw_ = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.foot_pw_ = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]
        """ LCM Type: float[4][3] """
        self.pf_init_ = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]
        """ LCM Type: float[4][3] """
        self.foot_vdes = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]
        """ LCM Type: float[4][3] """
        self.rpy_des_ = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.pf_rel = [ [ 0.0 for dim1 in range(2) ] for dim0 in range(4) ]
        """ LCM Type: float[4][2] """
        self.parse_data = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(planner_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>3f', *self.p_des[:3]))
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.foot_pDes[i0][:3]))
        buf.write(struct.pack('>3f', *self.pw_[:3]))
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.foot_pw_[i0][:3]))
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.pf_init_[i0][:3]))
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.foot_vdes[i0][:3]))
        buf.write(struct.pack('>3f', *self.rpy_des_[:3]))
        for i0 in range(4):
            buf.write(struct.pack('>2f', *self.pf_rel[i0][:2]))
        buf.write(struct.pack('>3f', *self.parse_data[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != planner_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return planner_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = planner_lcmt()
        self.p_des = struct.unpack('>3f', buf.read(12))
        self.foot_pDes = []
        for i0 in range(4):
            self.foot_pDes.append(struct.unpack('>3f', buf.read(12)))
        self.pw_ = struct.unpack('>3f', buf.read(12))
        self.foot_pw_ = []
        for i0 in range(4):
            self.foot_pw_.append(struct.unpack('>3f', buf.read(12)))
        self.pf_init_ = []
        for i0 in range(4):
            self.pf_init_.append(struct.unpack('>3f', buf.read(12)))
        self.foot_vdes = []
        for i0 in range(4):
            self.foot_vdes.append(struct.unpack('>3f', buf.read(12)))
        self.rpy_des_ = struct.unpack('>3f', buf.read(12))
        self.pf_rel = []
        for i0 in range(4):
            self.pf_rel.append(struct.unpack('>2f', buf.read(8)))
        self.parse_data = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if planner_lcmt in parents: return 0
        tmphash = (0xb8e474d594826486) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if planner_lcmt._packed_fingerprint is None:
            planner_lcmt._packed_fingerprint = struct.pack(">Q", planner_lcmt._get_hash_recursive([]))
        return planner_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", planner_lcmt._get_packed_fingerprint())[0]

