"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class quadruped_model_lcmt(object):

    __slots__ = ["pGC", "vGC", "base_omega", "base_vel", "base_pos", "base_rpy"]

    __typenames__ = ["float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[4, 3], [4, 3], [3], [3], [3], [3]]

    def __init__(self):
        self.pGC = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]
        """ LCM Type: float[4][3] """
        self.vGC = [ [ 0.0 for dim1 in range(3) ] for dim0 in range(4) ]
        """ LCM Type: float[4][3] """
        self.base_omega = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.base_vel = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.base_pos = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.base_rpy = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(quadruped_model_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.pGC[i0][:3]))
        for i0 in range(4):
            buf.write(struct.pack('>3f', *self.vGC[i0][:3]))
        buf.write(struct.pack('>3f', *self.base_omega[:3]))
        buf.write(struct.pack('>3f', *self.base_vel[:3]))
        buf.write(struct.pack('>3f', *self.base_pos[:3]))
        buf.write(struct.pack('>3f', *self.base_rpy[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != quadruped_model_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return quadruped_model_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = quadruped_model_lcmt()
        self.pGC = []
        for i0 in range(4):
            self.pGC.append(struct.unpack('>3f', buf.read(12)))
        self.vGC = []
        for i0 in range(4):
            self.vGC.append(struct.unpack('>3f', buf.read(12)))
        self.base_omega = struct.unpack('>3f', buf.read(12))
        self.base_vel = struct.unpack('>3f', buf.read(12))
        self.base_pos = struct.unpack('>3f', buf.read(12))
        self.base_rpy = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if quadruped_model_lcmt in parents: return 0
        tmphash = (0x95d1ba66b15a5764) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if quadruped_model_lcmt._packed_fingerprint is None:
            quadruped_model_lcmt._packed_fingerprint = struct.pack(">Q", quadruped_model_lcmt._get_hash_recursive([]))
        return quadruped_model_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", quadruped_model_lcmt._get_packed_fingerprint())[0]

