"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class rc_lcmt(object):

    __slots__ = ["mode", "p_des", "height_variation", "v_des", "rpy_des", "omega_des", "variables", "step_height"]

    __typenames__ = ["int32_t", "float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, [2], None, [3], [3], [3], [3], None]

    def __init__(self):
        self.mode = 0
        """ LCM Type: int32_t """
        self.p_des = [ 0.0 for dim0 in range(2) ]
        """ LCM Type: float[2] """
        self.height_variation = 0.0
        """ LCM Type: float """
        self.v_des = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.rpy_des = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.omega_des = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.variables = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.step_height = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(rc_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.mode))
        buf.write(struct.pack('>2f', *self.p_des[:2]))
        buf.write(struct.pack(">f", self.height_variation))
        buf.write(struct.pack('>3f', *self.v_des[:3]))
        buf.write(struct.pack('>3f', *self.rpy_des[:3]))
        buf.write(struct.pack('>3f', *self.omega_des[:3]))
        buf.write(struct.pack('>3f', *self.variables[:3]))
        buf.write(struct.pack(">f", self.step_height))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rc_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rc_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = rc_lcmt()
        self.mode = struct.unpack(">i", buf.read(4))[0]
        self.p_des = struct.unpack('>2f', buf.read(8))
        self.height_variation = struct.unpack(">f", buf.read(4))[0]
        self.v_des = struct.unpack('>3f', buf.read(12))
        self.rpy_des = struct.unpack('>3f', buf.read(12))
        self.omega_des = struct.unpack('>3f', buf.read(12))
        self.variables = struct.unpack('>3f', buf.read(12))
        self.step_height = struct.unpack(">f", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if rc_lcmt in parents: return 0
        tmphash = (0x3b0653e7596b6479) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if rc_lcmt._packed_fingerprint is None:
            rc_lcmt._packed_fingerprint = struct.pack(">Q", rc_lcmt._get_hash_recursive([]))
        return rc_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rc_lcmt._get_packed_fingerprint())[0]

