"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ros_lowstate_lcmt(object):

    __slots__ = ["q", "qd", "tauIq", "tauEst", "quat", "gyro", "accelerometer"]

    __typenames__ = ["float", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [[12], [12], [12], [12], [4], [3], [3]]

    def __init__(self):
        self.q = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.qd = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.tauIq = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.tauEst = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.quat = [ 0.0 for dim0 in range(4) ]
        """ LCM Type: float[4] """
        self.gyro = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """
        self.accelerometer = [ 0.0 for dim0 in range(3) ]
        """ LCM Type: float[3] """

    def encode(self):
        buf = BytesIO()
        buf.write(ros_lowstate_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>12f', *self.q[:12]))
        buf.write(struct.pack('>12f', *self.qd[:12]))
        buf.write(struct.pack('>12f', *self.tauIq[:12]))
        buf.write(struct.pack('>12f', *self.tauEst[:12]))
        buf.write(struct.pack('>4f', *self.quat[:4]))
        buf.write(struct.pack('>3f', *self.gyro[:3]))
        buf.write(struct.pack('>3f', *self.accelerometer[:3]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ros_lowstate_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ros_lowstate_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ros_lowstate_lcmt()
        self.q = struct.unpack('>12f', buf.read(48))
        self.qd = struct.unpack('>12f', buf.read(48))
        self.tauIq = struct.unpack('>12f', buf.read(48))
        self.tauEst = struct.unpack('>12f', buf.read(48))
        self.quat = struct.unpack('>4f', buf.read(16))
        self.gyro = struct.unpack('>3f', buf.read(12))
        self.accelerometer = struct.unpack('>3f', buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ros_lowstate_lcmt in parents: return 0
        tmphash = (0x87d7191a53d8e733) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ros_lowstate_lcmt._packed_fingerprint is None:
            ros_lowstate_lcmt._packed_fingerprint = struct.pack(">Q", ros_lowstate_lcmt._get_hash_recursive([]))
        return ros_lowstate_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ros_lowstate_lcmt._get_packed_fingerprint())[0]

