"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class sim_ground_truth_lcmt(object):

    __slots__ = ["p_w_", "v_w_", "q", "qd"]

    __typenames__ = ["float", "float", "float", "float"]

    __dimensions__ = [[6], [6], [12], [12]]

    def __init__(self):
        self.p_w_ = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.v_w_ = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """
        self.q = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """
        self.qd = [ 0.0 for dim0 in range(12) ]
        """ LCM Type: float[12] """

    def encode(self):
        buf = BytesIO()
        buf.write(sim_ground_truth_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6f', *self.p_w_[:6]))
        buf.write(struct.pack('>6f', *self.v_w_[:6]))
        buf.write(struct.pack('>12f', *self.q[:12]))
        buf.write(struct.pack('>12f', *self.qd[:12]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != sim_ground_truth_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sim_ground_truth_lcmt._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = sim_ground_truth_lcmt()
        self.p_w_ = struct.unpack('>6f', buf.read(24))
        self.v_w_ = struct.unpack('>6f', buf.read(24))
        self.q = struct.unpack('>12f', buf.read(48))
        self.qd = struct.unpack('>12f', buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if sim_ground_truth_lcmt in parents: return 0
        tmphash = (0x9a053180cfb1f6fc) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if sim_ground_truth_lcmt._packed_fingerprint is None:
            sim_ground_truth_lcmt._packed_fingerprint = struct.pack(">Q", sim_ground_truth_lcmt._get_hash_recursive([]))
        return sim_ground_truth_lcmt._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", sim_ground_truth_lcmt._get_packed_fingerprint())[0]

