"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class usb_data_t(object):

    __slots__ = ["chip1_data", "chip1_flg", "chip2_data", "chip2_flg", "chip3_data", "chip3_flg", "timestamp"]

    __typenames__ = ["float", "int32_t", "float", "int32_t", "float", "int32_t", "int64_t"]

    __dimensions__ = [[6, 5], [1], [6, 5], [1], [6, 5], [1], None]

    def __init__(self):
        self.chip1_data = [ [ 0.0 for dim1 in range(5) ] for dim0 in range(6) ]
        """ LCM Type: float[6][5] """
        self.chip1_flg = [ 0 for dim0 in range(1) ]
        """
        6 motors, 5 commands each
        LCM Type: int32_t[1]
        """

        self.chip2_data = [ [ 0.0 for dim1 in range(5) ] for dim0 in range(6) ]
        """ LCM Type: float[6][5] """
        self.chip2_flg = [ 0 for dim0 in range(1) ]
        """
        6 motors, 5 commands each
        LCM Type: int32_t[1]
        """

        self.chip3_data = [ [ 0.0 for dim1 in range(5) ] for dim0 in range(6) ]
        """ LCM Type: float[6][5] """
        self.chip3_flg = [ 0 for dim0 in range(1) ]
        """
        6 motors, 5 commands each
        LCM Type: int32_t[1]
        """

        self.timestamp = 0
        """ LCM Type: int64_t """

    def encode(self):
        buf = BytesIO()
        buf.write(usb_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(6):
            buf.write(struct.pack('>5f', *self.chip1_data[i0][:5]))
        buf.write(struct.pack('>1i', *self.chip1_flg[:1]))
        for i0 in range(6):
            buf.write(struct.pack('>5f', *self.chip2_data[i0][:5]))
        buf.write(struct.pack('>1i', *self.chip2_flg[:1]))
        for i0 in range(6):
            buf.write(struct.pack('>5f', *self.chip3_data[i0][:5]))
        buf.write(struct.pack('>1i', *self.chip3_flg[:1]))
        buf.write(struct.pack(">q", self.timestamp))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != usb_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return usb_data_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = usb_data_t()
        self.chip1_data = []
        for i0 in range(6):
            self.chip1_data.append(struct.unpack('>5f', buf.read(20)))
        self.chip1_flg = struct.unpack('>1i', buf.read(4))
        self.chip2_data = []
        for i0 in range(6):
            self.chip2_data.append(struct.unpack('>5f', buf.read(20)))
        self.chip2_flg = struct.unpack('>1i', buf.read(4))
        self.chip3_data = []
        for i0 in range(6):
            self.chip3_data.append(struct.unpack('>5f', buf.read(20)))
        self.chip3_flg = struct.unpack('>1i', buf.read(4))
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if usb_data_t in parents: return 0
        tmphash = (0x72e5d7e103d70683) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if usb_data_t._packed_fingerprint is None:
            usb_data_t._packed_fingerprint = struct.pack(">Q", usb_data_t._get_hash_recursive([]))
        return usb_data_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", usb_data_t._get_packed_fingerprint())[0]

