"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class usb_command_t(object):

    __slots__ = ["chip1_cmd", "chip1_flg", "chip2_cmd", "chip2_flg", "chip3_cmd", "chip3_flg"]

    __typenames__ = ["float", "int32_t", "float", "int32_t", "float", "int32_t"]

    __dimensions__ = [[6, 5], [1], [6, 5], [1], [6, 5], [1]]

    def __init__(self):
        self.chip1_cmd = [ [ 0.0 for dim1 in range(5) ] for dim0 in range(6) ]
        """ LCM Type: float[6][5] """
        self.chip1_flg = [ 0 for dim0 in range(1) ]
        """
        6 motors, 5 commands each
        LCM Type: int32_t[1]
        """

        self.chip2_cmd = [ [ 0.0 for dim1 in range(5) ] for dim0 in range(6) ]
        """ LCM Type: float[6][5] """
        self.chip2_flg = [ 0 for dim0 in range(1) ]
        """
        6 motors, 5 commands each
        LCM Type: int32_t[1]
        """

        self.chip3_cmd = [ [ 0.0 for dim1 in range(5) ] for dim0 in range(6) ]
        """ LCM Type: float[6][5] """
        self.chip3_flg = [ 0 for dim0 in range(1) ]
        """
        6 motors, 5 commands each
        LCM Type: int32_t[1]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(usb_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        for i0 in range(6):
            buf.write(struct.pack('>5f', *self.chip1_cmd[i0][:5]))
        buf.write(struct.pack('>1i', *self.chip1_flg[:1]))
        for i0 in range(6):
            buf.write(struct.pack('>5f', *self.chip2_cmd[i0][:5]))
        buf.write(struct.pack('>1i', *self.chip2_flg[:1]))
        for i0 in range(6):
            buf.write(struct.pack('>5f', *self.chip3_cmd[i0][:5]))
        buf.write(struct.pack('>1i', *self.chip3_flg[:1]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != usb_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return usb_command_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = usb_command_t()
        self.chip1_cmd = []
        for i0 in range(6):
            self.chip1_cmd.append(struct.unpack('>5f', buf.read(20)))
        self.chip1_flg = struct.unpack('>1i', buf.read(4))
        self.chip2_cmd = []
        for i0 in range(6):
            self.chip2_cmd.append(struct.unpack('>5f', buf.read(20)))
        self.chip2_flg = struct.unpack('>1i', buf.read(4))
        self.chip3_cmd = []
        for i0 in range(6):
            self.chip3_cmd.append(struct.unpack('>5f', buf.read(20)))
        self.chip3_flg = struct.unpack('>1i', buf.read(4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if usb_command_t in parents: return 0
        tmphash = (0xf499c331bb281864) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if usb_command_t._packed_fingerprint is None:
            usb_command_t._packed_fingerprint = struct.pack(">Q", usb_command_t._get_hash_recursive([]))
        return usb_command_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", usb_command_t._get_packed_fingerprint())[0]

